apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-spring-exam1
spec:
  replicas: 1 # 변경된 부분: replicas를 3개로 변경
  template:
    spec:
      containers:
        - name: k8s-spring-exam1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
