apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-spring-exam1
spec:
  template:
    spec:
      containers:
        - name: k8s-spring-exam1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
