apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: dev
resources:
- ../../base
images:
- name: hanumoka/k8s-spring-exam1
  newName: hanumoka/k8s-spring-exam1
  newTag: build-31-11c026f57342ee953b7675e07f6664887a400324
