apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment-patch.yaml
commonLabels:
  env: dev
resources:
- ../../base
images:
- name: hanumoka/k8s-spring-exam1
  newName: hanumoka/k8s-spring-exam1
  newTag: build-14-706830a03cdb917c309a84d192b8aa30c556c257
