apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: dev
resources:
- ../../base
images:
- name: hanumoka/k8s-spring-exam1
  newName: hanumoka/k8s-spring-exam1
  newTag: build-29-79c0d81c55bacd9e6f31374d07059ef240a42f26
