apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: dev
resources:
  - ../../base
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
images:
  - name: hanumoka/k8s-spring-exam1
    newName: hanumoka/k8s-spring-exam1
    newTag: build-36-f156ae6436a5f56c193296416318c56622006dbb
