apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-spring-exam1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-spring-exam1
  template:
    metadata:
      labels:
        app: k8s-spring-exam1
    spec:
      containers:
        - name: k8s-spring-exam1
          image: hanumoka/k8s-spring-exam1:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: docker-hub
