apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: hanumoka/k8s-spring-exam1
  newName: hanumoka/k8s-spring-exam1
  newTag: build-45-9beb21b64efa991107f79ec6ad6a02437cc4ee45
