apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: hanumoka/k8s-spring-exam1
  newName: hanumoka/k8s-spring-exam1
  newTag: build-47-5934849caf74588d302a6421642f27c2e3fd4bba
