apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage
commonLabels:
  env: stage
resources:
  - ../../base
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
